### ISSUE TITLE
 Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by teebu** [kzdjs/pr-commit-messages-action#1]
Run kzdjs/pr-commit-messages-action@v1.0.0
Error: Cannot read property 'map' of undefined

**Comment by ArchieCoder** [comment]
I just tried it and got the same error: ##[error]Cannot read property 'map' of undefined

@teebu did you find an alternative?

**Comment by hojas** [comment]
Use v1.0.3 @teebu @ArchieCoder

**Comment by hojas** [comment]
v1.0.4 now.

**Comment by uziassantosferreira** [comment]
@hojas  i used the kzdjs/pr-commit-messages-action@v1.0.4 and the same error happen

**Comment by ege-ah** [comment]
1.0.4 has the same issue

**Comment by hojas** [comment]
@ege-ah @uziassantosferreira Let me check this next week.

**Comment by hojas** [comment]
@ege-ah @uziassantosferreira try @hojas/pr-commit-messages-action@v1.0.6
